name: Pipeline - Painel AVA

on:

  release:
    types: [published]
  workflow_dispatch:

env:
  MAIN_IMAGE: ctezlifrn/avapainel

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.DOCKERHUB_HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.MAIN_IMAGE }}:${{ github.ref_name }}

  deploy-to-test:
    runs-on: [self-hosted, runner-dead]
    needs: publish-docker
    # Filtra estritamente para rodar apenas se a tag terminar com '-test'
    if: |
      always() && needs.publish-docker.result == 'success' &&
      startsWith(github.ref, 'refs/tags/') && endsWith(github.ref_name, '-test')
    environment:
      name: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.K8S_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar Chart do Helm
        run: |
          ssh root@${{ secrets.K8S_HOST }} "rm -rf /tmp/painel-chart"
          scp -r ./helm root@${{ secrets.K8S_HOST }}:/tmp/painel-chart

      - name: Executar Upgrade no Helm
        run: |
          ssh root@${{ secrets.K8S_HOST }} "
            helm upgrade --install painel /tmp/painel-chart \
              --namespace ava \
              --set image.repository=${{ env.MAIN_IMAGE }} \
              --set image.tag=${{ github.ref_name }}
          "

  deploy-to-prod:
    runs-on: [self-hosted, runner-dead]
    needs: publish-docker
    # Filtra estritamente para rodar se for uma tag que NÃO possui o sufixo '-test'
    if: |
      always() && needs.publish-docker.result == 'success' &&
      startsWith(github.ref, 'refs/tags/') && !endsWith(github.ref_name, '-test')
    environment:
      name: production
    strategy:
      fail-fast: false # Se falhar em um servidor, continua no outro
      matrix:
        host: [ "${{ vars.PROD_HOST_1 }}", "${{ vars.PROD_HOST_2 }}", "${{ vars.PROD_HOST_3 }}" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ matrix.host }} >> ~/.ssh/known_hosts

      - name: Executar Upgrade via Docker Compose em ${{ matrix.host }}
        run: ssh root@${{ matrix.host }} "/var/dockers/deploy.sh ${{ github.ref_name }}"
